language: node_js
node_js:
  - 16.13.0
install:
  - yarn
services:
  - docker

before_install:
  - docker build -t utardabest/youtube-stats -f Dockerfile .
  
script:
  - docker run utardabest/youtube-stats npm run build
  
